<?php

namespace JaiUneIdee\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
	public function getInvitationsByUser($user){
        $qb = $this->createQueryBuilder('i','u')
                    ->addSelect('i','u')
        			->leftJoin('i.user', 'u')
                    ->where('i.inviteur = '.$user->getId());
		return $qb->getQuery()->execute();
    }
    public function count24(){
        $qb = $this->createQueryBuilder('i');
        $qb->select('count(i.id)');
        $qb->andWhere('i.created_at >= :hier');
        $qb->setParameter('hier', new \DateTime('-1 day'));
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function count(){
        $qb = $this->createQueryBuilder('i');
        $qb->select('count(i.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
