lyra_admin:
    theme: ui-lightness
    models:
        idees:
            class: 'JaiUneIdee\SiteBundle\Entity\Idee'
            controller: 'JaiUneIdeeAdminBundle:Admin'
            filter:
              # show dialog title
              title: Search Listing
              fields:
                title: ~
                theme: ~
                user: ~
                is_published: ~
                is_removed: ~
                is_validated_by_admin: ~
                life: ~
                created_at: 
                  widget: daterange
                  options:
                    child_widget: date_picker
            show:
              # show dialog title
              title: Listing
              fields:
                title: ~
                theme: ~
                user: ~
                content: ~
                is_published: ~
                is_removed: ~
                is_validated_by_admin: ~
                life: ~
                created_at: 
                  label: Date
                  format: 'j/M/Y H:i:s'
            fields:
                created_at:
                    widget: datetime_picker
            form:
                groups:
                    listing:
                        # panel title
                        caption: Idee
                        fields: [title, theme, description, content]
                        # column break after this panel
                        break_after: true
                    status:
                        caption: Status
                        fields: [is_published,is_removed, is_validated_by_admin,life]
            list:
              title: Idées insérées
              max_page_rows: 15
              default_sort:
                column: created_at
                order: desc
              columns: 
                title: ~
                theme: ~
                user: ~
                is_published: ~
                is_removed: ~
                is_validated_by_admin: ~
                life: ~
                created_at: 
                  label: Date
                  format: 'j/M/Y H:i:s'
              batch_actions: [publish,unpublish,delete]
            actions:
                new:
                  text: 'Nouvelle Idée'
                  icon: circle-plus
                publish:
                    text: Publish
                unpublish:
                    text: Unpublish
        commentaires:
            class: 'JaiUneIdee\SiteBundle\Entity\Commentaire'
            controller: 'JaiUneIdeeAdminBundle:Admin'
            filter:
              # show dialog title
              title: Search Listing
              fields:
                idee: ~
                user: ~
                is_removed: ~
                is_validated_by_admin: ~
                life: ~
                created_at: 
                  widget: daterange
                  options:
                    child_widget: date_picker
            show:
              # show dialog title
              title: Listing
              fields:
                idee: ~
                user: ~
                content: ~
                is_removed: ~
                is_validated_by_admin: ~
                life: ~
                created_at: 
                  label: Date
                  format: 'j/M/Y H:i:s'
            fields:
                created_at:
                    widget: datetime_picker
            form:
                groups:
                    listing:
                        # panel title
                        caption: Commentaire
                        fields: [title, life, content]
                        # column break after this panel
                        break_after: true
                    status:
                        caption: Status
                        fields: [is_removed, is_validated_by_admin,life]
            list:
              title: Commentaires insérés
              max_page_rows: 15
              default_sort:
                column: created_at
                order: desc
              columns: 
                idee: ~
                user: ~
                is_removed: ~
                is_validated_by_admin: ~
                life: ~
                created_at: 
                  label: Date
                  format: 'j/M/Y H:i:s'
              batch_actions: [delete]
            actions: ~
        user:
            class: 'JaiUneIdee\UtilisateurBundle\Entity\User'
            # title displayed in top menu
            title: Users
            list:
                title: Listing users
                max_page_rows: 15
                default_sort:
                  column: username
                  order: asc
                columns:
                    username: ~
                    email: ~
                    dommage:
                      sortable: true
                    enabled: ~
#                    sexe:
#                      sortable: false
#                    tendance_politique:
#                      sortable: false
#                    lastLogin:
#                      sortable: true
                    last_activity:
                      format: 'j/M/Y H:i:s'
                      sortable: true
                    created_at:
                      sortable: true
            form:
                groups:
                    listing:
                        # panel title
                        caption: User
                        fields: [username, email]
                        # column break after this panel
                        break_after: true
                    status:
                        caption: Status
                        fields: [sexe, tendance_politique]
        tendance_politique:
            class: 'JaiUneIdee\UtilisateurBundle\Entity\TendancePolitique'
            # title displayed in top menu
            title: Tendances Politiques
            list:
                title: Tendances politiques
                columns:
                    value: ~
        theme:
            class: 'JaiUneIdee\SiteBundle\Entity\Theme'
            # title displayed in top menu
            title: Thèmes
            list:
                title: Thèmes
                columns:
                    nom: ~
                    descriptif: ~
                    is_moderated: ~
                    ordre: ~
        invitation:
            class: 'JaiUneIdee\UtilisateurBundle\Entity\Invitation'
            # title displayed in top menu
            title: Invitations
            list:
                title: Invitations
                max_page_rows: 15
#                default_sort:
#                  column: id
#                  order: desc
                columns:  
                  #id: ~
                  email: ~
                  sent: ~
                  #user: ~
                  inviteur: ~
        news:
            class: 'JaiUneIdee\SiteBundle\Entity\News'
            # title displayed in top menu
            title: News
            list:
                title: News
                columns:
                    publication_date: ~
                    is_validated_by_admin: ~
                    is_removed: ~
                    updated_at: ~
            form:
                groups:
                    listing:
                        # panel title
                        caption: News
                        fields: [content, publication_date]
                        # column break after this panel
                        break_after: true
                    status:
                        caption: Status
                        fields: [is_validated_by_admin, is_removed]