#JaiUneIdee\UtilisateurBundle\Entity\User:
#    constraints:
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: invitation
#    properties:
#        invitation:
#            - NotNull: 
#               message: Votre code d'identification est faux.
JaiUneIdee\UtilisateurBundle\Entity\User:
    properties:
        avatar:
            - Image:
                groups: [avatar]
                maxSize: 10M
                minWidth: 50
                maxWidth: 10000
                minHeight: 50
                maxHeight: 10000
