JaiUneIdee\SiteBundle\Entity\ActionElu:
  type: entity
  repositoryClass: JaiUneIdee\SiteBundle\Repository\ActionEluRepository
  table: action_elu
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    date_jaime:
      type: datetime
      nullable: true
    jaime:
      type: boolean
      nullable: false
      options:
        default: false
    date_jemengage:
      type: datetime
      nullable: true
    jemengage:
      type: boolean
      nullable: false
      options:
        default: false
    date_jairealise:
      type: datetime
      nullable: true
    jairealise:
      type: boolean
      nullable: false
      options:
        default: false
    date_jenaimepas:
      type: datetime
      nullable: true
    jenaimepas:
      type: boolean
      nullable: false
      options:
        default: false
  manyToOne:
    idee:
      targetEntity: Idee
      inversedBy: actionsElus
    user:
      targetEntity: JaiUneIdee\UtilisateurBundle\Entity\User
      joinColumn:
        onDelete: CASCADE