JaiUneIdee\SiteBundle\Entity\AlerteIdee:
  type: entity
  repositoryClass: JaiUneIdee\SiteBundle\Repository\AlerteIdeeRepository
  table: alerte_idee
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    activated:
      type: boolean
      nullable: false
      options:
        default: true
    created_at:
      type: datetime
      nullable: false
      options:
        default: '1990-01-01 00:00:00'
  manyToOne:
    idee:
      targetEntity: Idee
      joinColumn:
        onDelete: CASCADE
    user:
      targetEntity: JaiUneIdee\UtilisateurBundle\Entity\User
      joinColumn:
        onDelete: CASCADE
  lifecycleCallbacks: {  }
