JaiUneIdee\SiteBundle\Entity\Commentaire:
  type: entity
  repositoryClass: JaiUneIdee\SiteBundle\Repository\CommentaireRepository
  table: commentaire
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    content:
      type: text
      nullable: false
    is_validated_by_admin:
      type: boolean
      nullable: false
      options:
        default: false
    life:
      type: integer
      options:
        default: 500
    is_removed:
      type: boolean
      nullable: false
      options:
        default: false
    is_moderated:
      type: boolean
      nullable: false
      options:
        default: false
    created_at:
      type: datetime
      nullable: false      
      options:
        default: '1990-01-01 00:00:00'
    updated_at:
      type: datetime
      nullable: false
      options:
        default: '1990-01-01 00:00:00'
  manyToOne:
    idee:
      targetEntity: Idee
      inversedBy: commentaires
      joinColumn:
        onDelete: CASCADE
    user:
      targetEntity: JaiUneIdee\UtilisateurBundle\Entity\User
      joinColumn:
        onDelete: CASCADE
    moderations:
      targetEntity: ModerationCommentaire
      mappedBy: commentaire
#    vote:
#      targetEntity: Vote
#      joinColumns:
#        joinColumn:
#          name: user
#          referencedColumnName: user
#        joinColumn:
#          name: idee
#          referencedColumnName: idee
  lifecycleCallbacks:
    preUpdate: [ setUpdatedValue ]
