JaiUneIdee\SiteBundle\Entity\Idee:
  type: entity
  repositoryClass: JaiUneIdee\SiteBundle\Repository\IdeeRepository
  table: idee
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    slug:
      type: string
      lenght: 255
      nullable: false
    title:
      type: string
      lenght: 255
      nullable: false
    description:
      type: string
      lenght: 140
      nullable: false
    content:
      type: text
      nullable: false
    is_published:
      type: boolean
      nullable: false
      options:
        default: false
    is_removed:
      type: boolean
      nullable: false
      options:
        default: false
    created_at:
      type: datetime
      nullable: false
    updated_at:
      type: datetime
      nullable: false
    last_action_at:
      type: datetime
      nullable: false
      options:
        default: '1990-01-01 00:00:00'
    is_validated_by_admin:
      type: boolean
      nullable: false
      options:
        default: false
    is_moderated:
      type: boolean
      nullable: false
      options:
        default: false
    life:
      type: integer
      options:
        default: 2000
  oneToMany:
    votes:
      targetEntity: Vote
      mappedBy: idee
    moderations:
      targetEntity: Moderation
      mappedBy: idee
    commentaires:
      targetEntity: Commentaire
      mappedBy: idee
    actionsElus:
      targetEntity: ActionElu
      mappedBy: idee
  manyToOne:
    theme:
      targetEntity: Theme
    user:
      targetEntity: JaiUneIdee\UtilisateurBundle\Entity\User
      joinColumn:
        onDelete: CASCADE
  manyToMany:
    localisations:
      targetEntity: JaiUneIdee\LocalisationBundle\Entity\Localisation
      joinTable:
        name: idee_localisation
        joinColumns:
          idee_id:
            referencedColumnName: id
        inverseJoinColumns:
          localisation_id:
            referencedColumnName: id
  lifecycleCallbacks:
    preUpdate: [ setUpdatedValue ]
