parameters:
#    jai_une_idee_localisation.example.class: JaiUneIdee\LocalisationBundle\Example

services:
    jaiuneidee.localisation.form.data_transformer:
        class: JaiUneIdee\LocalisationBundle\Form\DataTransformer\LocalisationsToIdsTransformer
        arguments: [@doctrine.orm.entity_manager]
    jaiuneidee.localisation.form.type:
        class: JaiUneIdee\LocalisationBundle\Form\Type\LocalisationFormType
        arguments: [@jaiuneidee.localisation.form.data_transformer]
        tags: [{ name: "form.type", alias: "jaiuneidee_localisation_type" }]
    localisation_request_listener:
        class: JaiUneIdee\LocalisationBundle\Listener\RequestListener
        arguments: [@doctrine.orm.entity_manager,%main_site%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    localisation.listener:
        class: JaiUneIdee\LocalisationBundle\Listener\LocalisationListener
        tags:
            - { name: doctrine.orm.entity_listener }