imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: @JaiUneIdeeAdminBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          %secret%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    session:
        cookie_lifetime: 0
        save_path: %kernel.root_dir%/cache/sessions
        cookie_domain: .%main_site%
        name: %cookies_name%
#    trust_proxy_headers: false

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      main_site: %main_site%

# Assetic Configuration
assetic:
#    bundles: ~ 
#    debug:          %kernel.debug%
    use_controller: false
#    java: /usr/bin/java
    filters:
        cssrewrite: ~
#         closure:
#             jar: %kernel.root_dir%/java/compiler.jar
#         yui_css:
#             jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        query_cache_driver:    apc
        metadata_cache_driver: apc
        result_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: JaiUneIdee\UtilisateurBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
      form:
        type: jaiuneidee_user_registration
#        handler: jai_une_idee_utilisateur.form.handler.registration
      # Permet la validation automatique du compte par envoi d'un email
      confirmation:
        enabled:    true
        from_email:
          # Adresse de l'expediteur
          address:        noreply@jaiuneidee.net
          # Nom de l'expediteur
          sender_name:    Admin de jaiuneidee.net
        # Permet de définir le template de l'email à envoyer (en html)
        template: JaiUneIdeeUtilisateurBundle:User:registration.email.twig
    profile:
      form:
        type: jaiuneidee_user_profile_edit
services: 
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
 
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
gregwar_image: ~
fos_elastica:
    clients:
        default: { host: %es_host%, port: %es_port% }
#    serializer:
#        callback_class: FOS\ElasticaBundle\Serializer\Callback
#        serializer: serializer
    indexes:
        jaiuneidee:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_french_analyzer:
                                type: custom
                                tokenizer: letter
                                filter: ["asciifolding", "lowercase", "french_stem", "stop_fr"]
                        filter:
                            stop_fr:
                                type: "stop"
                                stopwords: ["l", "m", "t", "qu", "n", "s", "j", "d"]
            types:
                Idee:
                    mappings:
                        id:
                            type: integer
                        updatedAt :
                            type : date
                        lastAction :
                            type : date
                        theme : ~
                        localisations: ~
                        localisationsNiveau0: ~
                        localisationsNiveau1: ~
                        localisationsNiveau2: ~
                        localisationsNiveau3: ~
                        isVisible :
                            type : boolean
                        countCommentaires:
                            type: integer
                        title : { analyzer: custom_french_analyzer }
                        slug : ~ 
                        description : { analyzer: custom_french_analyzer }
                        content : { analyzer: custom_french_analyzer }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  JaiUneIdee\SiteBundle\Entity\Idee
                        provider: ~
                        listener: ~ # by default, listens to "insert", "update" and "delete"
                        finder: ~
                        repository: JaiUneIdee\SiteBundle\SearchRepository\IdeeRepository