<?php

namespace JaiUneIdee\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModerationCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerationCommentaireRepository extends EntityRepository
{ 
	public function getModerationByCommentaireAndUser($commentaire, $user){
        $qb = $this->createQueryBuilder('m')
                    ->where('m.commentaire = '.$commentaire->getId())
                    ->andWhere('m.user = '.$user->getId());
        return $qb->getQuery()->getResult();
	}
    public function getModerationByCommentaire($commentaire){
        $qb = $this->createQueryBuilder('m')
                    ->where('m.commentaire = '.$commentaire->getId());
        return $qb->getQuery()->getResult();
    }
}