<?php

namespace JaiUneIdee\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getNewsPublicQb(){
        $qb = $this->createQueryBuilder('n')
                    ->where('n.publication_date < :date')
                    ->andWhere('n.is_validated_by_admin = true')
                    ->andWhere('n.is_removed = false')
                    ->orderBy('n.publication_date', 'DESC')
                    ->setParameter('date', new \DateTime());
        return $qb;
    }
    public function getNewsPublicToday(){
        $qb = $this->createQueryBuilder('n')
                    ->where('n.publication_date < :date')
                    ->andWhere('n.publication_date >= :hier')
                    ->andWhere('n.is_validated_by_admin = true')
                    ->andWhere('n.is_removed = false')
                    ->orderBy('n.publication_date', 'DESC')
                    ->setParameter('date', new \DateTime())
                    ->setParameter('hier', new \DateTime('-1 day'));
        return $qb->getQuery()->execute();
    }
}
