<?php

namespace JaiUneIdee\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
	public function findAll()
	{
		$qb = $this->createQueryBuilder('t');
        $qb->select('t')
        			->orderBy('t.ordre');
        return $qb->getQuery()->execute();
	}
}