<?php

namespace JaiUneIdee\LocalisationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationRepository extends EntityRepository
{
	public function getListe($param)
    {
        $qb = $this->createQueryBuilder('l');
        $qb->select("l.id, CONCAT(l.nom, CONCAT(".$qb->expr()->literal(' (').", CONCAT(CASE WHEN p.nom IS NULL THEN 'Pays entier' ELSE p.nom END,".$qb->expr()->literal(')')."))) as nom");
        $qb->add('where', $qb->expr()->like('UPPER(l.nom)','UPPER(:param)'))
           ->addOrderBy('l.population', 'ASC')
           ->addOrderBy('l.niveau', 'ASC')
           ->addOrderBy('l.nom', 'ASC');
        $qb->leftjoin('l.parent', 'p');
        $qb->setParameter('param', '%'.$param.'%');
    	return $qb->getQuery()->getArrayResult();
    }
    public function getListeSousDomaine()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->andWhere('l.urlName IS NOT NULL')
           ->addOrderBy('l.population', 'ASC')
           ->addOrderBy('l.niveau', 'ASC')
           ->addOrderBy('l.nom', 'ASC');
    	return $qb->getQuery()->getResult();
    }
}