JaiUneIdee\UtilisateurBundle\Entity\User:
  type: entity
  repositoryClass: JaiUneIdee\UtilisateurBundle\Repository\UserRepository
  table: fos_user
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    created_at:
      type: datetime
      nullable: false
      options:
        default: '1990-01-01 00:00:00'
    last_activity:
      type: datetime
      nullable: false
      options:
        default: '1990-01-01 00:00:00'
    date_de_naissance:
      type: date
    date_de_naissance_public:
      type: boolean
      nullable: false
      options:
        default: false
    approbation_charte:
      type: boolean
      nullable: false
    sexe_public:
      type: boolean
      nullable: false
      options:
        default: false
    localisation_public:
      type: boolean
      nullable: false
      options:
        default: false
    tendance_politique_public:
      type: boolean
      nullable: false
      options:
        default: false
    newsletter:
      type: boolean
      nullable: false
      options:
        default: true
    avatar:
      type: string
      nullable: true
      options:
        default: ""
      length: 255
  oneToOne:
    invitation:
      targetEntity: Invitation
      nullable: false
      inversedBy: user
      joinColumn:
        name: invitation_code
        referencedColumnName: id
  manyToOne:
    sexe:
      targetEntity: Sexe
      nullable: false
    tendance_politique:
      targetEntity: TendancePolitique
    dommage:
      targetEntity: Dommage
      nullable: true
    localisation:
      targetEntity: JaiUneIdee\LocalisationBundle\Entity\Localisation
      nullable: false
    localisationRecherchee:
      targetEntity: JaiUneIdee\LocalisationBundle\Entity\Localisation
      nullable: true
  oneToMany:
    invitations:
      targetEntity: Invitation
      mappedBy: inviteur
  lifecycleCallbacks:
    preUpdate: [uploadAvatar ]
    prePersist: [uploadAvatar ]
    postPersist: [ moveImage ]
    preRemove: [removeImage]
#CSP
#liste de thèmes préférés
#revenus moyens