<?php

namespace JaiUneIdee\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DommageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DommageRepository extends EntityRepository
{
	public function getUserDefaultDommage()
    {
        $qb = $this->createQueryBuilder('d')
                    ->where('d.level = 10')
                    ;
        return $qb->getQuery()->getOneOrNullResult();
    }
    public function getUserNextDommage($currentlevel)
    {
        $qb = $this->createQueryBuilder('d')
                    ->where('d.level >= :currentLevel')
                    ->orderBy('d.level', 'ASC')
                    ->setParameter('currentLevel', $currentlevel)
                    ->setMaxResults(2)
                    ;
        $result = $qb->getQuery()->getResult();
        $result = array_pop($result);
        return  $result;
    }
    public function getUserPreviousDommage($currentlevel)
    {
        $qb = $this->createQueryBuilder('d')
                    ->where('d.level <= :currentLevel')
                    ->orderBy('d.level', 'DESC')
                    ->setParameter('currentLevel', $currentlevel)
                    ->setMaxResults(4)
                    ;
        $result = $qb->getQuery()->getResult();
        $result = array_pop($result);
        return  $result;
    }
}