<?php

namespace JaiUneIdee\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TendancePolitiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TendancePolitiqueRepository extends EntityRepository
{
}