<?php

namespace JaiUneIdee\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAll(){
        $qb = $this->createQueryBuilder('u');
        $qb->andWhere('u.enabled = true');
        return $qb->getQuery()->execute();
    }
    public function findAllForNewsletter(){
        $qb = $this->createQueryBuilder('u');
        $qb->andWhere('u.enabled = true');
        $qb->andWhere('u.newsletter = true');
        return $qb->getQuery()->execute();
    }
    public function countUtilisateursConnectes24(){
        $qb = $this->createQueryBuilder('u');
        $qb->select('count(u.id)');
        $qb->andWhere('u.last_activity >= :hier');
        $qb->andWhere('u.enabled = true');
        $qb->setParameter('hier', new \DateTime('-1 day'));
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function countInscrit24(){
        $qb = $this->createQueryBuilder('u');
        $qb->select('count(u.id)');
        $qb->andWhere('u.created_at >= :hier');
        $qb->andWhere('u.enabled = true');
        $qb->setParameter('hier', new \DateTime('-1 day'));
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function countInscrit(){
        $qb = $this->createQueryBuilder('u');
        $qb->select('count(u.id)');
        $qb->andWhere('u.enabled = true');
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
}