<?php

namespace JaiUneIdee\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlerteIdeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteIdeeRepository extends EntityRepository
{
    public function getAlerteIdeeByIdeeAndUser($idee, $user){
        $qb = $this->createQueryBuilder('a')
                    ->where('a.idee = :idee_id')
                    ->andWhere('a.user = :user_id')
                    ->setParameter('idee_id', $idee->getId())
                    ->setParameter('user_id', $user->getId());
        return $qb->getQuery()->getOneOrNullResult();
    }
    public function getAbonnesIdee($idee){
        $qb = $this->createQueryBuilder('a')
                    ->where('a.idee = :idee_id')
                    ->andWhere('a.activated = true')
                    ->setParameter('idee_id', $idee->getId())
                ;
        return $qb->getQuery()->execute();
    }
    public function count24(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('count(a.id)');
        $qb->andWhere('a.created_at >= :hier');
        $qb->andWhere('a.activated = true');
        $qb->setParameter('hier', new \DateTime('-1 day'));
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function count(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('count(a.id)');
        $qb->andWhere('a.activated = true');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
