<?php

namespace JaiUneIdee\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerationRepository extends EntityRepository
{
	public function getModerationByIdeeAndUser($idee, $user){
        $qb = $this->createQueryBuilder('m')
                    ->where('m.idee = '.$idee->getId())
                    ->andWhere('m.user = '.$user->getId());
        return $qb->getQuery()->getResult();
        
    }
    public function getModerationByIdee($idee){
        $qb = $this->createQueryBuilder('m')
                    ->where('m.idee = '.$idee->getId());
        return $qb->getQuery()->getResult();
    }
}